import test from 'node:test';
import assert from 'node:assert/strict';
import { DevelopmentWishStore, DemoDurations, WishDomainError, WishStatuses, expiryFromServer, groupWishes, snapshotProduct, summarizeWishes } from '../src/app/wish-domain.js';
import { AuthService } from '../src/app/auth-service.js';
import { buildWishScenario, wishTestNames } from '../src/app/wish-test-scenarios.js';

const product = { itemId: 'i-1', title: '测试商品', price: 100, finalPrice: 88, promotionUrl: 'https://example.test/item' };
const evidence = { expert: [], experience: [] };
const key = (n) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;

test('phase5 durations and product snapshot are controlled', () => { assert.deepEqual(DemoDurations, [24,48,72]); assert.equal(snapshotProduct(product).estimatedPrice, 88); assert.equal(snapshotProduct({ ...product, promotionUrl: 'javascript:x' }), null); });
test('phase5 create is idempotent and capped at five active wishes', () => { const store = new DevelopmentWishStore(); const first = store.create({ product, evidence, duration:24, idempotencyKey:key(1) }); assert.equal(store.create({ product, evidence, duration:24, idempotencyKey:key(1) }).id, first.id); for(let i=2;i<=5;i++) store.create({product,evidence,duration:24,idempotencyKey:key(i)}); assert.throws(() => store.create({product,evidence,duration:24,idempotencyKey:key(6)}), (e) => e.code === 'active_limit_reached'); });
test('phase5 restores absolute expiry and expires sealed wishes', () => { let now=0; const store=new DevelopmentWishStore({now:()=>now}); const wish=store.create({product,evidence,duration:24,idempotencyKey:key(1)}); now=24_000; assert.equal(store.list()[0].status, WishStatuses.EXPIRED); assert.equal(expiryFromServer(wish.expiresAt, now), 0); });
test('phase5 decision first write wins and abandonment counts once', () => { let now=0; const store=new DevelopmentWishStore({now:()=>now}); const wish=store.create({product,evidence,duration:24,idempotencyKey:key(1)}); now=25_000; store.list(); assert.equal(store.decide(wish.id,'abandon').countedAmount, 88); assert.equal(store.decide(wish.id,'purchase').status, WishStatuses.ABANDONED); assert.equal(summarizeWishes(store.list()).abandonedListedAmount,88); });
test('phase5 purchase intent does not count as abandoned amount', () => { let now=0; const store=new DevelopmentWishStore({now:()=>now}); const wish=store.create({product,evidence,duration:24,idempotencyKey:key(1)}); now=25_000; store.list(); assert.equal(store.decide(wish.id,'purchase').countedAmount,0); assert.equal(summarizeWishes(store.list()).abandonedListedAmount,0); });
test('phase5 groups, sorts and pages wishes', () => { const scenario=buildWishScenario('pagination',0); const result=groupWishes(scenario.store.list(), {page:0,pageSize:20,now:1_000_000}); assert.equal(result.items.length,20); assert.equal(result.hasMore,true); assert.ok(result.groups.completed.length); });
test('phase5 development scenarios are explicit and local', () => { assert.equal(wishTestNames.length,19); for(const name of wishTestNames) assert.ok(buildWishScenario(name)); });
test('phase5 auth initialization deduplicates anonymous login', async () => { let calls=0; const client={auth:{getUser:async()=>({data:{user:null},error:null}),signInAnonymously:async()=>{calls++;return {data:{user:{id:'u',is_anonymous:true}},error:null};}}}; const auth=new AuthService({url:'https://example.test',publishableKey:'key',client}); const [a,b]=await Promise.all([auth.ensureSession(),auth.ensureSession()]); assert.equal(a.id,b.id); assert.equal(calls,1); });
test('phase5 existing-email login always disables automatic signup', async () => { let options; const client={auth:{getSession:async()=>({data:{session:null}}),signInWithOtp:async(value)=>{options=value.options;return {error:null};}}}; const auth=new AuthService({url:'https://example.test',publishableKey:'key',client}); await auth.requestExistingLogin('user@example.test'); assert.equal(options.shouldCreateUser,false); });
test('phase5 invalid transition remains rejected', () => { const store=new DevelopmentWishStore(); assert.throws(() => store.create({product,evidence,duration:12,idempotencyKey:key(1)}), (e)=>e.code==='invalid_duration'); });
