import test from 'node:test';
import assert from 'node:assert/strict';
import { DevelopmentWishStore, DemoDurations, WishDomainError, WishStatuses, expiryFromServer, groupWishes, snapshotProduct, summarizeWishes } from '../src/app/wish-domain.js';
import { AuthService } from '../src/app/auth-service.js';
import { buildWishScenario, createWishTestHarness, wishTestNames } from '../src/app/wish-test-scenarios.js';
import { RecoveryTriggers, recoveryPlan, recoveryTarget } from '../src/app/wish-recovery.js';
import { States } from '../src/app/state-machine.js';
import { Views } from '../src/app/navigation.js';

const product = { itemId: 'i-1', title: '测试商品', price: 100, finalPrice: 88, promotionUrl: 'https://s.click.taobao.com/item' };
const evidence = { expert: [], experience: [] };
const key = (n) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;

test('phase5 durations and product snapshot are controlled', () => { assert.deepEqual(DemoDurations, [24,48,72]); assert.equal(snapshotProduct(product).estimatedPrice, 88); assert.equal(snapshotProduct({ ...product, promotionUrl: 'javascript:x' }), null); });
test('phase5 create is idempotent and capped at five active wishes', () => { const store = new DevelopmentWishStore(); const first = store.create({ product, evidence, duration:24, idempotencyKey:key(1) }); assert.equal(store.create({ product, evidence, duration:24, idempotencyKey:key(1) }).id, first.id); for(let i=2;i<=5;i++) store.create({product,evidence,duration:24,idempotencyKey:key(i)}); assert.throws(() => store.create({product,evidence,duration:24,idempotencyKey:key(6)}), (e) => e.code === 'active_limit_reached'); });
test('phase5 restores absolute expiry and expires sealed wishes', () => { let now=0; const store=new DevelopmentWishStore({now:()=>now}); const wish=store.create({product,evidence,duration:24,idempotencyKey:key(1)}); now=24_000; assert.equal(store.list()[0].status, WishStatuses.EXPIRED); assert.equal(expiryFromServer(wish.expiresAt, now), 0); });
test('phase5 decision first write wins and abandonment counts once', () => { let now=0; const store=new DevelopmentWishStore({now:()=>now}); const wish=store.create({product,evidence,duration:24,idempotencyKey:key(1)}); now=25_000; store.list(); assert.equal(store.decide(wish.id,'abandon').countedAmount, 88); assert.equal(store.decide(wish.id,'purchase').status, WishStatuses.ABANDONED); assert.equal(summarizeWishes(store.list()).abandonedListedAmount,88); });
test('phase5 purchase intent does not count as abandoned amount', () => { let now=0; const store=new DevelopmentWishStore({now:()=>now}); const wish=store.create({product,evidence,duration:24,idempotencyKey:key(1)}); now=25_000; store.list(); assert.equal(store.decide(wish.id,'purchase').countedAmount,0); assert.equal(summarizeWishes(store.list()).abandonedListedAmount,0); });
test('phase5 groups, sorts and pages wishes', async () => { const scenario=createWishTestHarness('pagination',0); const outcome=await scenario.run(); const result=groupWishes(scenario.store.list(), {page:0,pageSize:20,now:1_000_000}); assert.equal(outcome.count,22); assert.equal(result.items.length,20); assert.equal(result.hasMore,true); assert.ok(result.groups.completed.length); });
test('phase5 development scenarios are explicit local behaviors', async () => { assert.ok(wishTestNames.includes('purchase-invalid-link')); for(const name of wishTestNames) { const harness=createWishTestHarness(name, 0); assert.ok(harness); if (name !== 'refresh-restore') assert.ok(await harness.run()); } });
test('phase5 behavioral scenarios change local data and expose stable results', async () => {
  const duplicate=await createWishTestHarness('duplicate-create',0).run(); assert.deepEqual(duplicate,{code:'duplicate_created_once',count:1,sameId:true});
  const race=await createWishTestHarness('decision-race',0).run(); assert.equal(race.code,'first_decision_wins'); assert.equal(race.winner,WishStatuses.PURCHASED_INTENT); assert.equal(race.secondStatus,WishStatuses.PURCHASED_INTENT);
  const cleared=await createWishTestHarness('clear-wishes',0).run(); assert.equal(cleared.count,1); assert.equal(cleared.activePreserved,true); assert.equal(cleared.status,WishStatuses.SEALED);
  const deleted=await createWishTestHarness('delete-wish',0).run(); assert.equal(deleted.count,1);
  const bound=await createWishTestHarness('bind-email',0).run(); assert.equal(bound.ownerUnchanged,true); assert.equal(bound.anonymous,false);
  const login=await createWishTestHarness('existing-email-login',0).run(); assert.equal(login.shouldCreateUser,false);
  const migrated=await createWishTestHarness('migration',0).run(); assert.equal(migrated.movedCount,2); assert.equal(migrated.sourceCount,0); assert.equal(migrated.targetCount,3); assert.equal(migrated.repeatMovedCount,0);
  const migrationError=await createWishTestHarness('migration-error',0).run(); assert.deepEqual(migrationError,{ok:false,code:'migration_failed',sourceCount:2,targetCount:1});
  for (const name of ['otp-error','otp-expired','otp-rate-limited']) { const result=await createWishTestHarness(name,0).run(); assert.equal(result.retryable,true); assert.match(result.code,/^otp_/); }
  const account=createWishTestHarness('account-delete',0); assert.equal((await account.run()).code,'confirmation_required'); assert.deepEqual(await account.run(),{code:'account_deleted',count:0,deleted:true});
});
test('phase5 refresh test scenario preserves its absolute expiry from a fixed seed', () => { const first=buildWishScenario('refresh-restore',1_000); const restored=buildWishScenario('refresh-restore',1_000); assert.equal(first.refreshExpiresAt,restored.refreshExpiresAt); assert.equal(first.store.list()[0].expiresAt,restored.store.list()[0].expiresAt); });
test('phase5 recovery derives view from stored active wishes without a memory record id', () => { let now=0; const store=new DevelopmentWishStore({now:()=>now}); const sealed=store.create({product,evidence,duration:24,idempotencyKey:key(1)}); const one=recoveryTarget(store.list()); assert.equal(one.record.id,sealed.id); assert.equal(one.state,WishStatuses.SEALED); const other=store.create({product,evidence,duration:48,idempotencyKey:key(2)}); const many=recoveryTarget(store.list()); assert.equal(many.reason,'multiple_active'); assert.equal(many.record,null); now=25_000; store.list(); const expired=recoveryTarget([store.list().find((wish)=>wish.id===sealed.id)]); assert.equal(expired.state,WishStatuses.EXPIRED); assert.equal(expired.record.expiresAt,sealed.expiresAt); assert.ok(other); });
test('phase5 initial recovery restores one server-active wish and preserves its absolute expiry', () => { const store=new DevelopmentWishStore({now:()=>0}); const sealed=store.create({product,evidence,duration:24,idempotencyKey:key(101)}); const plan=recoveryPlan({trigger:RecoveryTriggers.INITIAL_LOAD,currentView:Views.FLOW,currentState:States.IDLE,currentRecordId:null,wishes:store.list()}); assert.equal(plan.action,'replace_view'); assert.equal(plan.view,Views.FLOW); assert.equal(plan.record.id,sealed.id); assert.equal(plan.record.expiresAt,sealed.expiresAt); assert.equal(plan.state,States.SEALED); });
test('phase5 background recovery cannot replace a second product search with an older wish', () => { const store=new DevelopmentWishStore({now:()=>0}); const oldWish=store.create({product,evidence,duration:24,idempotencyKey:key(102)}); const plan=recoveryPlan({trigger:RecoveryTriggers.BACKGROUND_RETURN,currentView:Views.FLOW,currentState:States.PRODUCT_SEARCHING,currentRecordId:null,wishes:store.list()}); assert.equal(plan.action,'keep_current'); assert.equal(plan.reason,'protected_current_flow'); assert.equal(oldWish.status,WishStatuses.SEALED); const afterReload=recoveryPlan({trigger:RecoveryTriggers.INITIAL_LOAD,currentView:Views.FLOW,currentState:States.PRODUCT_SEARCHING,currentRecordId:null,wishes:store.list()}); assert.equal(afterReload.action,'replace_view'); assert.equal(afterReload.record.id,oldWish.id); });
test('phase5 background wish views refresh only their own server data and multiple-active reload opens the list', () => { const store=new DevelopmentWishStore({now:()=>0}); const first=store.create({product,evidence,duration:24,idempotencyKey:key(103)}); const refreshCurrent=recoveryPlan({trigger:RecoveryTriggers.BACKGROUND_RETURN,currentView:Views.FLOW,currentState:States.SEALED,currentRecordId:first.id,wishes:store.list()}); assert.equal(refreshCurrent.action,'refresh_current'); assert.equal(refreshCurrent.record.expiresAt,first.expiresAt); const refreshList=recoveryPlan({trigger:RecoveryTriggers.BACKGROUND_RETURN,currentView:Views.WISHES,currentState:States.IDLE,currentRecordId:null,wishes:store.list()}); assert.equal(refreshList.action,'refresh_wishes'); store.create({product,evidence,duration:48,idempotencyKey:key(104)}); const reload=recoveryPlan({trigger:RecoveryTriggers.INITIAL_LOAD,currentView:Views.FLOW,currentState:States.IDLE,currentRecordId:null,wishes:store.list()}); assert.equal(reload.action,'replace_view'); assert.equal(reload.view,Views.WISHES); assert.equal(reload.reason,'multiple_active'); });
test('phase5 first visit treats AuthSessionMissingError as normal anonymous creation', async () => { let calls=0; const client={auth:{getUser:async()=>({data:{user:null},error:{name:'AuthSessionMissingError',message:'Auth session missing!'}}),signInAnonymously:async()=>{calls++;return {data:{user:{id:'u',is_anonymous:true}},error:null};}}}; const auth=new AuthService({url:'https://example.test',publishableKey:'key',client}); const [a,b]=await Promise.all([auth.ensureSession(),auth.ensureSession()]); assert.equal(a.id,b.id); assert.equal(calls,1); });
test('phase5 existing anonymous and linked-email sessions are reused', async () => { for (const user of [{id:'anonymous',is_anonymous:true},{id:'linked',is_anonymous:false}]) { let calls=0; const auth=new AuthService({url:'https://example.test',publishableKey:'key',client:{auth:{getUser:async()=>({data:{user},error:null}),signInAnonymously:async()=>{calls++;return {data:{user:null},error:null};}}}}); assert.equal((await auth.ensureSession()).id,user.id); assert.equal(calls,0); } });
test('phase5 existing-email login always disables automatic signup', async () => { let options; const client={auth:{getSession:async()=>({data:{session:null}}),signInWithOtp:async(value)=>{options=value.options;return {error:null};}}}; const auth=new AuthService({url:'https://example.test',publishableKey:'key',client}); await auth.requestExistingLogin('user@example.test'); assert.equal(options.shouldCreateUser,false); });
test('phase5 invalid transition remains rejected', () => { const store=new DevelopmentWishStore(); assert.throws(() => store.create({product,evidence,duration:12,idempotencyKey:key(1)}), (e)=>e.code==='invalid_duration'); });
test('phase5 refreshed state preserves exact expiresAt and completed clear leaves active wishes', () => { let now=0; const store=new DevelopmentWishStore({now:()=>now}); const sealed=store.create({product,evidence,duration:24,idempotencyKey:key(1)}); const initialExpiry=sealed.expiresAt; assert.equal(store.list()[0].expiresAt,initialExpiry); now=25_000; store.list(); store.decide(sealed.id,'abandon'); const active=store.create({product,evidence,duration:48,idempotencyKey:key(2)}); store.clearCompleted(); assert.equal(store.list().length,1); assert.equal(store.list()[0].id,active.id); });
test('phase5 blocks unapproved promotion URLs and invalid decisions', () => { const store=new DevelopmentWishStore(); assert.equal(snapshotProduct({...product,promotionUrl:'https://example.test/x'}),null); const wish=store.create({product,evidence,duration:24,idempotencyKey:key(1)}); assert.throws(()=>store.decide(wish.id,'rewrite'), (error)=>error.code==='invalid_decision'); });
